### ISSUE TITLE
Revisar Tarea 

### ISSUE THREAD

**Issue by LachoCardenas44** [LachoCardenas44/Aprendiendo-React-Ejemplo-Basico#1]

**Comment by yosbel-penate** [comment]
Buen trabajo estas listo para algo más serio

**Comment by yosbel-penate** [comment]
?

**Comment by LachoCardenas44** [comment]
Si ,he estado un poco complicado con problemas familiares pero ya estoy 100% libre

**Comment by yosbel-penate** [comment]
perfecto lee los mensajes que he ido dejando en [Espacio de discusiones sobre el proyecto Transport-Link](https://github.com/orgs/Bluemoonside/teams/transportlink-team/discussions/1)
